/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.littlepay;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

class AppTest {
    private final PrintStream standardOut = System.out;
    private final ByteArrayOutputStream outputStreamCaptor = new ByteArrayOutputStream();

    @BeforeEach
    public void setUp() {
        System.setOut(new PrintStream(outputStreamCaptor));
    }

    @AfterEach
    public void tearDown() {
        System.setOut(standardOut);
    }

    @Test
    void appHasCorrectOutput() {
        Path resourceDirectory = Paths.get("src","test","resources","taps.csv");
        String absolutePath = resourceDirectory.toFile().getAbsolutePath();
        String[] args = { absolutePath };

        App.main(args);

        // assertEquals("Started, Finished, DurationSecs, FromStopId, ToStopId, ChargeAmount, CompanyId, BusID, PAN, Status", outputStreamCaptor.toString().trim());
    }
}
